version: '3'

networks:
  nestjsx_crud_e2e:

services:
  postresql:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nestjsx_crud_e2e
    networks:
      - nestjsx_crud_e2e

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    command: redis-server
    networks:
      - nestjsx_crud_e2e
